spring.application.name=admls-api-gateway
server.port=8085

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.routes[0].id=library-service
spring.cloud.gateway.routes[0].uri=lb://LIBRARY-API-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/library/**