spring.application.name=admls-api-gateway
server.port=8085

spring.cloud.gateway.discovery.locator.enabled=false

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.routes[0].id=document-by-id
spring.cloud.gateway.routes[0].uri=lb://library-api-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/library/documents/{id}
spring.cloud.gateway.routes[0].filters[0]=SetPath=/documents/{id}